administrasi/administrasi/urls.py
from django.contrib import admin
from django.urls import path, include
from surat_menyurat import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('home/', views.home, name='home'),    
    path('surat/', include('surat_menyurat.urls', namespace="surat")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrasi/surat_menyurat/urls.py
from django.urls import path, include
from . import views

app_name ='surat_menyurat'

urlpatterns = [
  path('arsipsuratmasuk/', views.arsip_surat_masuk_list, name='arsip_surat_masuk_list'),
  # path('arsipsuratmasukdelete/<int:id>', views.arsip_surat_masuk_delete, name='arsip_surat_masuk_delete'),
  path('arsipsuratkeluar/', views.arsip_surat_keluar_list, name='arsip_surat_keluar_list'),
  # path('arsipsuratkeluardelete/<int:id>', views.arsip_surat_keluar_delete, name='arsip_surat_keluar_delete'),
  
  path('suratmasuk/', views.surat_masuk_list, name='surat_masuk_list'),
  path('suratmasukform/', views.surat_masuk_form, name='surat_masuk_form'),
  # path('suratmasukdelete/<int:id>', views.surat_masuk_delete, name='surat_masuk_delete'),
  # path('suratmasukedit/<int:id>', views.surat_masuk_edit, name='surat_masuk_edit'),

  path('suratkeluar/', views.surat_keluar_list, name='surat_keluar_list'),
  path('suratkeluarform/', views.surat_keluar_form, name='surat_keluar_form'),
  # path('suratkeluardelete/<int:id>', views.surat_keluar_delete, name='surat_keluar_delete'),
  # path('suratkeluaredit/<int:id>', views.surat_keluar_edit, name='surat_keluar_edit'),
]

administrasi/surat_menyurat/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Surat(models.Model):
  nomor         = models.CharField(max_length=255, blank=False, null=False)
  tgl_surat     = models.CharField(
                  _("Tanggal surat"),
                  help_text=_('Tanggal di dalam isi surat'),
                  max_length=255, blank=False, null=False)
  perihal       = models.CharField(max_length=255, blank=False, null=False)
  pengirim      = models.CharField(
                  help_text=_('Orang atau jasa yang mengantar surat'),
                  max_length=255, blank=True, null=True)
  deskripsi     = models.TextField(blank=True, null=True)
  file_path     = models.FileField(blank=True, null=True, upload_to='surat_menyurat/medias/')

class SuratMasuk(Surat):
  STATUS_MASUK = (
    ('Baru Masuk', 'Masuk'),
    ('Diproses ke Kepala Dinas', 'Diproses ke Kepala Dinas'),
    ('Diproses ke Sekretaris Dinas', 'Diproses ke Sekretaris Dinas'),
    ('Diproses bidang terkait', 'Diproses Bidang Terkait'),
  )
  tgl_masuk     = models.CharField(
                  _("Tanggal masuk"),
                  help_text=_('Tanggal masuk surat ke kantor'),
                  max_length=255, blank=False, null=False)
  status        = models.CharField(max_length=255, choices=STATUS_MASUK)
  created       = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated       = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __str__(self):
    return self.nomor

class SuratKeluar(Surat):
  STATUS_KELUAR = (
    ('Sudah Dikirim', 'Sudah Dikirim'),
    ('Diproses ke Kepala Dinas', 'Diproses ke Kepala Dinas'),
    ('Diproses ke Sekretaris Dinas', 'Diproses ke Sekretaris Dinas'),
    ('Diproses bidang terkait', 'Diproses Bidang Terkait'),
  )
  tgl_keluar        = models.CharField(
                      _("Tanggal keluar"),
                      help_text=_('Tanggal keluar surat dari kantor'),
                      max_length=255, blank=False, null=False)
  status            = models.CharField(max_length=255, choices=STATUS_KELUAR)
  created           = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated           = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __str__(self):
    return self.nomor

administrasi/templates/surat/arsip_surat_keluar_list.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Arsip surat keluar</small>
</h4>
<br />
<form method="GET" class="form-inline mb-3">
  <input type="text" name="q" class="form-control mr-sm-2" placeholder="Cari..." value="{{ request.GET.q }}">

  <label for="start_date" class="mr-sm-2">Mulai dari:</label>
  <input type="date" name="start_date" id="start_date" class="form-control mr-sm-2"
    value="{{ request.GET.start_date }}">

  <label for="end_date" class="mr-sm-2">Sampai:</label>
  <input type="date" name="end_date" id="end_date" class="form-control mr-sm-2" value="{{ request.GET.end_date }}">

  <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
</form>
<br />
<div class="table-responsive">
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Status</th>
        <th scope="col">Tanggal Keluar</th>
        <th scope="col">Pembaruan</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for dt in data %}
    <tbody>
      <tr>
        <td scope="col">{{ forloop.counter }}</td>
        <td scope="row">{{ dt.nomor }}</td>
        <td>{{dt.tgl_surat}}</td>
        <td>{{dt.perihal}}</td>
        <td>{{dt.pengirim}}</td>
        <td>{{dt.deskripsi}}</td>
        <td>{{dt.status}}</td>
        <td>{{dt.tgl_keluar}}</td>
        <td>{{dt.updated}}</td>
        <td>
          {% if dt.file_path %}
          <a href="http://127.0.0.1:8000/media/{{ dt.file_path }}" target="_blank">Lihat File</a><br /><br />
          {% endif %}
          <a onclick="return confirm('Delete data?')" href="">Hapus</a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock content %}

administrasi/templates/surat/arsip_surat_masuk_list.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Arsip surat masuk</small>
  <!-- <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_masuk_form' %}" class="btn btn-outline-primary">Tambah data</a>
  </small> -->
</h4>
<br />
<form method="GET" action="{% url 'surat:arsip_surat_masuk_list' %}" class="form-inline mb-3">
  <input type="text" name="q" class="form-control mr-sm-2" placeholder="Cari..." value="{{ request.GET.q }}">

  <label for="start_date" class="mr-sm-2">Mulai dari:</label>
  <input type="date" name="start_date" id="start_date" class="form-control mr-sm-2"
    value="{{ request.GET.start_date }}">

  <label for="end_date" class="mr-sm-2">Sampai:</label>
  <input type="date" name="end_date" id="end_date" class="form-control mr-sm-2" value="{{ request.GET.end_date }}">

  <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
</form>
<br />
<div class="table-responsive">
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Status</th>
        <th scope="col">Tanggal Masuk</th>
        <th scope="col">Pembaruan</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for dt in data %}
    <tbody>
      <tr>
        <td scope="col">{{ forloop.counter }}</td>
        <td scope="row">{{ dt.nomor }}

        </td>
        <td>{{dt.tgl_surat}}</td>
        <td>{{dt.perihal}}</td>
        <td>{{dt.pengirim}}</td>
        <td>{{dt.deskripsi}}</td>
        <td>{{dt.status}}</td>
        <td>{{dt.tgl_masuk}}</td>
        <td>{{dt.updated}}</td>
        <td>
          {% if dt.file_path %}
          <a href="http://127.0.0.1:8000/media/{{ dt.file_path }}" target="_blank">Lihat File</a><br /><br />
          {% endif %}
          <a onclick="return confirm('Delete data?')" href="">Hapus</a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock content %}

administrasi/templates/surat/surat_keluar_form_edit.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Form edit surat keluar</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_keluar_list' %}" class="btn btn-outline-primary">List data</a>
  </small>
</h4>
<br />
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped table-hover">
    <input type="hidden" value="{{ id }}" name="id" />
    {{form.as_table}}
  </table>
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock content %}

administrasi/templates/surat/surat_keluar_form_new.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Form surat keluar</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_keluar_list' %}" class="btn btn-outline-primary">List data</a>
  </small>
</h4>
<br />
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped table-hover">
    {{form.as_table}}
  </table>
  <button class="btn btn-primary" type="submit">Submit</button>
</form>

<script>
  $(function () {
    $("#id_tgl_keluar").datepicker({
      dateFormat: "dd-mm-yy",
    });
    $("#id_tgl_surat").datepicker({
      dateFormat: "dd-mm-yy",
    });
  });
</script>
{% endblock content %}

administrasi/templates/surat/surat_keluar_list.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">List surat keluar</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_keluar_form' %}" class="btn btn-outline-primary">Tambah data</a>
  </small>
</h4>
<br />
<form method="GET" action="{% url 'surat:surat_keluar_list' %}" class="form-inline mb-3">
  <input type="text" name="q" class="form-control mr-sm-2" placeholder="Cari..." value="{{ request.GET.q }}">

  <label for="start_date" class="mr-sm-2">Mulai dari:</label>
  <input type="date" name="start_date" id="start_date" class="form-control mr-sm-2"
    value="{{ request.GET.start_date }}">

  <label for="end_date" class="mr-sm-2">Sampai:</label>
  <input type="date" name="end_date" id="end_date" class="form-control mr-sm-2" value="{{ request.GET.end_date }}">

  <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
</form>
<br />
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Status</th>
        <th scope="col">Tanggal Keluar</th>
        <th scope="col">Pembaruan</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for dt in data %}
    <tbody>
      <tr>
        <td scope="col">{{ forloop.counter }}</td>
        <td scope="row">{{ dt.nomor }}</td>
        <td>{{dt.tgl_surat}}</td>
        <td>{{dt.perihal}}</td>
        <td>{{dt.pengirim}}</td>
        <td>{{dt.deskripsi}}</td>
        <td>{{dt.status}}</td>
        <td>{{dt.tgl_keluar}}</td>
        <td>{{dt.updated}}</td>
        <td>
          {% if dt.file_path %}
          <a href="http://127.0.0.1:8000/media/{{ dt.file_path }}" target="_blank">Lihat File</a><br /><br />
          {% endif %}
          <a href="">Edit</a> |
          <a onclick="return confirm('Delete data?')" href="">Hapus</a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock content %}

administrasi/templates/surat/surat_masuk_form_edit.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Form edit surat masuk</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_masuk_list' %}" class="btn btn-outline-primary">List data</a>
  </small>
</h4>
<br />
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped table-hover">
    <input type="hidden" value="{{ id }}" name="id" />
    {{form.as_table}}
  </table>
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock content %}

administrasi/templates/surat/surat_masuk_form_new.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">Form surat masuk</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_masuk_list' %}" class="btn btn-outline-primary">List data</a>
  </small>
</h4>
<br />
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped table-hover">
    {{form.as_table}}
  </table>
  <button class="btn btn-primary" type="submit">Submit</button>
</form>

<script>
  $(function () {
    $("#id_tgl_masuk").datepicker({
      dateFormat: "dd-mm-yy",
    });
    $("#id_tgl_surat").datepicker({
      dateFormat: "dd-mm-yy",
    });
  });
</script>
{% endblock content %}

administrasi/templates/surat/surat_masuk_list.html
{% extends "base.html" %} {% block content %}
<h4>
  <small class="text-muted">List surat masuk</small>
  <small class="text-muted" style="float: right">
    <a href="{% url 'surat:surat_masuk_form' %}" class="btn btn-outline-primary">Tambah data</a>
  </small>
</h4>
<br />
<form method="GET" class="form-inline mb-3">
  <input type="text" name="q" class="form-control mr-sm-2" placeholder="Cari..." value="{{ request.GET.q }}">

  <label for="start_date" class="mr-sm-2">Mulai dari:</label>
  <input type="date" name="start_date" id="start_date" class="form-control mr-sm-2"
    value="{{ request.GET.start_date }}">

  <label for="end_date" class="mr-sm-2">Sampai:</label>
  <input type="date" name="end_date" id="end_date" class="form-control mr-sm-2" value="{{ request.GET.end_date }}">

  <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
</form>
<br />
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Nomor</th>
        <th scope="col">Tanggal surat</th>
        <th scope="col">Perihal</th>
        <th scope="col">Pengirim/Jasa</th>
        <th scope="col">Deksripsi</th>
        <th scope="col">Status</th>
        <th scope="col">Tanggal Masuk</th>
        <th scope="col">Pembaruan</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for dt in data %}
    <tbody>
      <tr>
        <td scope="col">{{ forloop.counter }}</td>
        <td scope="row">{{ dt.nomor }}

        </td>
        <td>{{dt.tgl_surat}}</td>
        <td>{{dt.perihal}}</td>
        <td>{{dt.pengirim}}</td>
        <td>{{dt.deskripsi}}</td>
        <td>{{dt.status}}</td>
        <td>{{dt.tgl_masuk}}</td>
        <td>{{dt.updated}}</td>
        <td>
          {% if dt.file_path %}
          <a href="http://127.0.0.1:8000/media/{{ dt.file_path }}" target="_blank">Lihat File</a><br /><br />
          {% endif %}
          <a href="">Edit</a> |
          <a onclick="return confirm('Delete data?')" href="">Hapus</a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock content %}